name: Python application

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Customer:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Customer Lifetime Value'
        # Default value if no value is explicitly provided
        default: "Across all products"
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run main code
      env: 
        account_name: ${{ secrets.ACCOUNT_NAME }}
        pass_key : ${{ secrets.PASSWORD }}
        user_name : ${{ secrets.USER_NAME }}
        warehouse : ${{ secrets.WAREHOUSE_NAME }}
        access : ${{ secrets.ACCESS_KEY }}
        bucket : ${{ secrets.BUCKET }}
        secret : ${{ secrets.SECRET_KEY }}
      run: |
        # python src/operate.py -db True
        # python src/opreate.py -t customer -i cust.csv
        # python src/operate.py -s3 customer.csv -i cust.csv
        # python src/opreate.py -t transaction -i tx_product.csv
        # python src/operate.py -s3 transaction.csv -si tx_product.csv
        # python src/operate.py -t original -i original.csv
        # python src/operate.py -s3 original.csv -si original.csv
        # python src/EDA.py
        python src/snowflake_table.py
